create database db_ecommerce;
use db_ecommerce;

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION CHAR(255) NOT NULL
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT PRIMARY KEY,
    ID_IMPUESTO INT,
    ID_CATEGORIA INT,
    NOMBRE VARCHAR(255),
    EXISTENCIA INT,
    PRECIO_PRODUCTO BLOB,
    DESCUENTO DECIMAL(10, 2),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE ORDEN (
    ID_ORDEN INT PRIMARY KEY,
    ID_CLIENTE INT,
    FECHA_ORDEN DATE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE CARRITO (
    ID_LINEA_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCTO INT,
    ID_ORDEN INT,
    CANTIDAD INT NOT NULL,
    PRECIO_PRODUCTO DECIMAL(10, 2) NOT NULL,
    DESCUENTO DECIMAL(10, 2),
    MONTO DECIMAL(10, 2),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN(ID_ORDEN)
);

CREATE TABLE METODO_PAGO (
    ID_METODO_PAGO INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_METODO VARCHAR(255) NOT NULL
);

CREATE TABLE TARJETA_CREDITO_DEBITO (
    ID_TARJETA INT AUTO_INCREMENT PRIMARY KEY,
    ID_METODO_PAGO INT,
    ID_CLIENTE INT,
    NOMBRE_TITULAR VARCHAR(255) NOT NULL,
    NUMERO_TARJETA VARCHAR(255) NOT NULL,
    FECHA_EXPIRACION DATE NOT NULL,
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO(ID_METODO_PAGO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ORDEN_PAGO (
    ID_ORDEN_PAGO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ORDEN INT,
    ID_METODO_PAGO INT,
    FECHA_PAGO DATE NOT NULL,
    MONTO_TOTAL DECIMAL(10, 2),
    FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN(ID_ORDEN),
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO(ID_METODO_PAGO)
);

show tables;

SELECT C.NOMBRE, O.FECHA_ORDEN, P.NOMBRE, P.PRECIO_PRODUCTO
FROM CLIENTE C
JOIN ORDEN O ON C.ID_CLIENTE = O.ID_CLIENTE
JOIN CARRITO CA ON O.ID_ORDEN = CA.ID_ORDEN
JOIN PRODUCTO P ON CA.ID_PRODUCTO = P.ID_PRODUCTO;
